services:
  birdapp: 
    build:
        context: ./birdlist
        dockerfile: BirdApp.Dockerfile 
    ports:
      - "8080:8080" 
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.41-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: birdlist
      MYSQL_USER: local_user
      MYSQL_PASSWORD: passWOWKIWI
    volumes:
      - birdvol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  birdvol:
